### PR TITLE
Improve error message on standalone if missing Boost.Config

### LINKED ISSUE #490: Better standalone error message?
When using the standalone, I get:

```
In file included from ./include/boost/multiprecision/mpfr.hpp:9:
In file included from ./include/boost/multiprecision/number.hpp:10:
./include/boost/multiprecision/detail/standalone_config.hpp:15:10: fatal error: 'boost/config.hpp' file not found
#include <boost/config.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```

This *is* an expected error:

```
// Boost.Config is dependency free so it is considered a requirement to use Boost.Multiprecision in standalone mode
#include <boost/config.hpp>
```

but could it give a nice error message as to why it's not supported using `__has_include`?

### PR DESCRIPTION
**Pull request by mborland**
Fixes #490

### CODE REVIEW

**Comment by jzmaddock** [comment]
The CircleCI failure is fixed in https://github.com/boostorg/quickbook/commit/071a58488d265c8a3f4d539196ee16c8db7e2769, which is to say not our problem.

Thanks for this Matt!

**Comment by mborland** [comment]
@jzmaddock This should be good now. Other than the CI failure you mentioned their is one stemming from a [concept failure in Boost.Filesystem.](https://github.com/boostorg/multiprecision/runs/8117686288?check_suite_focus=true#step:17:212)

**Comment by jzmaddock** [comment]
Looks like https://github.com/boostorg/filesystem/commit/b219d9fb8af760b54b014d1223ebd5d43b4d07b5, I've left a comment.
